### PR TITLE
Create a script to run analysis on Windows

### PR DESCRIPTION
**Pull request by pNovikau**

### CODE REVIEW

**Comment by DiamondDragon** [comment]
* I like idea of introducing `workflows.json`.  It looks like easy way to adopt available analysis to needs of specific project
* I think we can simplify adding of new workflows if we name folders with analysis as items in `workflow.json`. Each workflow inside folder should be named as `analysis.yaml`. In this way we may use principle "conventions over configurations".
* At the moment I see one difficulty when it comes to different tools whey may require different parameters. Some of them may not need `SolutionRelativePath` parameter. Others may need reference to something else (folder, package file and etc). There are two alternatives how we can deal with this:
   * Just put `run.ps1` (or bash script) in each folder which contains analysis. This is most simple and flexible way to support all differences. Main problem for end user is a need to run mutiple `run.ps1` files for single project. I think we can mitigate this problem by having few scripts which executes predefined set of analyses which may sense for .NET App. **This option is my preference**.
   * Other option is to use some generic parameter `target`. In this case all analyses may lost their flexibility.

**Comment by DiamondDragon** [comment]
Typical analysis workflow should output the following artefacts:
* *.sqlite database containing discovered issues
* *.json document containing data used to generate report
* *.html report which contains human-friendly interpretation of results.

**Review by DiamondDragon — DISMISSED** [review]
I suggest to merge this PR and create next one which reflects all comments described above.

**Comment by pNovikau** [comment]
> Typical analysis workflow should output the following artefacts:
> 
>     * *.sqlite database containing discovered issues
> 
>     * *.json document containing data used to generate report
> 
>     * *.html report which contains human-friendly interpretation of results.

This is what I gonna do in the next PR.

**Review by DiamondDragon — APPROVED** [review]
Looks good to me

**Pull request merged**
